### ISSUE TITLE
Problem when aligning text

### ISSUE THREAD

**Issue by karlog100** [sphilee/jsPDF-CustomFonts-support#20]
Hello, first thanks for your great plugin!

I got my ".ttf" fonts added to jsPDF, and working. But your version of jsPDF have issues with text alignment.

`doc.text(190, 76, "SomeText", 0, "right");`
Do not work in your version of jsPDF, but works fine in the new debug version of jsPDF (version 1.3.5), I have not been able to use your plugin with the debug version, could anyone inform me what to do, implement your plugin with jsPDF 1.3.5 debug? 

When using alignment of the text(with your version of jsPDF v1.3), I will get an error like: "Uncaught TypeError: Cannot read property 'width' of undefined" from split_text_to_size.js on line 47

**Comment by sphilee** [comment]
@karlog100 Can you give me a bunch of code for what font you wrote? I'll check it out.

**Comment by sphilee** [comment]
@karlog100 Could you check it out? I just fixed it.

**Comment by karlog100** [comment]
Sorry for the late reply, I expected to get an email on replies. 

The problem still seems to exist when I use your nevest version.

I cannot send you the font file as I do not own the license my self, but my customer does. 

The font is "MaxLF-Light" and "MaxLF-Bold" both seams to work fine with your system until I try to use alignment in the text.

`
doc.splitTextToSize("customer", 190);
doc.addFont("MaxLF-Bold.ttf", "MaxLF-Bold", "normal", "WinAnsiEncoding");
doc.addFont("MaxLF-Light.ttf", "MaxLF-Light", "normal", "WinAnsiEncoding");
doc.setFontSize(11);
doc.setFont("MaxLF-Light");
doc.addImage(imgData, 'JPEG', 120, -10, 74, 105);
//Adding page frame
doc.rect(10, 9, 190, 279);
doc.text(20, 48, $("#firstname").val() + ' ' + $("#lastname").val());
doc.text(20, 53, $("#address").val());
doc.text(20, 58, $("#zip").val() + '  ' + $("#city").val());

//Pasing date to patteren given, to make new patterens look at: https://github.com/datejs/Datejs
//doc.text(190, 76, "some right aligned text here", 0, "right");

//Adding title
doc.setFont("MaxLF-Bold");
doc.setFontSize(12);
doc.text(20, 100, pdfContent[0]);
var text;
doc.setFontSize(11);
doc.setFont("MaxLF-Light");
//adding text content
text = "lots of text here";
doc.text(20, 109, text);

//DEBUG
doc.save("save", 'two-by-four.pdf');
`

If I uncomment this:
`//doc.text(190, 76, "some right aligned text here", 0, "right");`

I get this error:
![jspdf custom error with text alignment](https://user-images.githubusercontent.com/6792335/32181525-d8b3a9e8-bd94-11e7-97fe-27da8fa3bc66.png)

**Comment by karlog100** [comment]
To everyone else, the issue is now fixed.

**Comment by nitinimistry** [comment]
I'm using jsPDF 1.4.1 and this issue still persists.
I set the custom font to "OpenSans" all works fine.
But when I come to line 
> doc.text("Some text", 10, 20, "right")
I get the same error
![jspdf-error](https://user-images.githubusercontent.com/32808628/45592800-1f3a9a00-b995-11e8-9b35-834525ea5588.png)

But if I remove the "right" alignment, then there's no error and PDF is generated.
